# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baa7f4c74b2694c109dca69a00ff965ecdc5e0513b866a923ca59330ce4863798773d78f29e6163dc2815491f94f5f4b7278cd941600fe0fe7d7de47c7f7f3ae

test:
  secret_key_base: f2c1aece5414ae1b8df4c1f5cc44e354075acc06534ee151fc53ae749923f0412f6037527153a89b17eee853d195eccd8b8f92afe892e5b6d88dcad42b84fab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
